[project]
name = "crawl4ai-demo"
version = "0.1.0"
description = "crawl4ai demo share"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.2.0",
    "ruff>=0.12.7",
]


[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
